### ISSUE TITLE
Wrong version?

### ISSUE THREAD

**Issue by EyreFree** [EFPrefix/EFStorage#3]
Version is 0.3.0 in [EFStorage.podspec of release/0.3.1](https://github.com/EFPrefix/EFStorage/blob/0.3.1/EFStorage.podspec), mistake?

![](https://user-images.githubusercontent.com/10757132/70493788-d47de280-1b43-11ea-9673-f98200941d0f.png)

**Comment by ApolloZhu** [comment]
Fixed in 0.3.2
